### ISSUE TITLE
would be cool to dogeify the title from the post being tipped

### ISSUE THREAD

**Issue by ghost** [nformant1/AirDoge2000#1]
It would be cool to have the bot comment on posts being tipped, for example using the title as input the latest 5 bot tipped posts would be:

- such Million. many Doges. much Rich. amaze.
- such Friday. such Feeling. amaze.
- such thought. wow.
- how Elon. very Musk. much Ðogecoin. very CEO. excite.
- very Crypto. many trader. so rough. how 🐶. wow.

This code can be used to dogeify a string.  Found at https://github.com/mitchtech/py_dogeify/blob/master/doge.py

    import nltk
    import re
    import random
    
    doge_adjectives = ["so", "such", "very", "much", "many", "how"]
    doge_emotions = ["wow", "amaze", "excite"]
    
    
    def dogeify(text):
        doge_msg = []
        sentences = re.split(r' *[\.\?!][\'"\)\]]* *', text)
    
        for sentence in sentences:
            if sentence == '':
                break
    
            doge_sentence = []
            tagged_set = nltk.pos_tag(sentence.split())
    
            allnouns = [word for word, pos in tagged_set if pos == 'NN' or pos == 'NNP' or pos == 'NNS' or pos == 'JJ']
    
            for word in allnouns:
                phrase = doge_adjectives[random.randint(0, 5)] + " " + word.strip(',\'') + "."
                doge_sentence.append(phrase)
    
            emotion = doge_emotions[random.randint(0, 2)] + "."
            doge_sentence.append(emotion)
            # print " ".join(doge_sentence)
    
            doge_msg.append(" ".join(doge_sentence))
        return " ".join(doge_msg)
    
    
    if __name__ == '__main__':
        print(dogeify("One Million Doges Rich"))
        print(dogeify("Friday Feeling"))
        print(dogeify("A thought"))
        print(dogeify("Elon Musk is Ðogecoin CEO ???"))
        print(dogeify("Being a Crypto trader can be rough 🐶"))

**Comment by nformant1** [comment]
Added to the code with some other changes
