### ISSUE TITLE
bot replies would look more coherent if limited to 3 nouns

### ISSUE THREAD

**Issue by ghost** [nformant1/AirDoge2000#2]
### proposed change
After line 50:

https://github.com/nformant1/AirDoge2000/blob/bb6ef3e456ae848c6f40065276b2ef197c8a14f4/AirDoge2000.py#L50

Adding this condition to limit the doge response to 3:

    if len(doge_sentence) >= 3:
        break

### examples

old

    very Congress. much digital. such dollar. so I’m. such goin. much everyone. much group. very active. such dogecoin. much 🐶. excite.
    how Musk. such Man. so Crypto. how Currency. how pic. excite.

new

    very Congress. much digital. such dollar. excite.
    how Musk. such Man. so Crypto. excite.

**Comment by nformant1** [comment]
Thanks, it has been added to the master branch and is online 👍
